Cleanup install.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -8,7 +8,9 @@
 
 # ignore installing those files, they are not to be symlinked
 GLOBIGNORE='.:..:.DS_Store:.git:.gitignore'
-HOMEBREW_PACKAGES="the_silver_searcher fzf autoenv tree vim"
+HOMEBREW_PACKAGES="autoenv curl fzf git git-extras nvm the_silver_searcher
+tmux tree vim"
+NPM_GLOBALS="grunt gulp browserify jshint"
 
 is_installed () {
   # This works with scripts and programs. For more info, check
@@ -36,25 +38,7 @@ install_homebrew () {
   done
 }
 
-install_git () {
-  if ! is_installed git; then
-    echo "installing git."
-    brew install git
-  fi
-
-  if ! is_installed git-extras; then
-    echo "installing git extras"
-    brew install git-extras
-  fi
-}
-
 install_node () {
-  # This one is a script
-  if ! is_brew_installed nvm; then
-    echo "installing nvm"
-    brew install nvm
-  fi
-
   if ! is_installed node; then
     echo "installing node with nvm."
     nvm install node
@@ -62,37 +46,17 @@ install_node () {
     # reclaim ownership of the ~/.npm module
     sudo chown -R $(whoami) ~/.npm
 
-    npm install -g grunt
-    npm install -g gulp
-    npm install -g browserify
-    npm install -g jshint
+    echo "installing node packages"
+    npm install -g "${NPM_GLOBALS}"
   fi
-}
-
-install_curl () {
-  is_installed curl || brew install curl
 }
 
 install_oh_my_zsh () {
-  if ! is_installed zsh; then
-    brew install zsh
+  if ! [[ -d ~/.oh-my-zsh ]] ; then
+    sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
 
     # make zsh default shell
     chsh -s `which zsh`
-  fi
-
-  if ! [[ -d ~/.oh-my-zsh ]] ; then
-    install_curl
-    sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
-
-    # plugins
-    brew install autoenv
-  fi
-}
-
-install_tmux () {
-  if ! is_installed tmux; then
-    brew install tmux
   fi
 }
 
@@ -138,11 +102,9 @@ main () {
 
   if ! [ "$#" -ne 0 ]; then
     echo "=============================="
-    echo "Installing missing packages:"
+    echo "Installing missing packages: $HOMEBREW_PACKAGES"
     install_homebrew
-    install_git
     install_node
-    install_tmux
     install_oh_my_zsh
     echo ""
   fi
